### ISSUE TITLE
cross posting from audiolib about cubeb failure

### ISSUE THREAD

**Issue by NHQ** [jussi-kalliokoski/node-cubeb#2]
please see https://github.com/jussi-kalliokoski/audiolib.js/issues/73

**Comment by NHQ** [comment]
Update. 

I got cubeb installed, tried to install node-cubeb via npm. Seemed to work, but

> cubeb = require('cubeb')
> Error: libcubeb.so.0: cannot open shared object file: No such file or directory
>     at Object.Module._extensions..node (module.js:485:11)
>     at Module.load (module.js:356:32)
>     at Function.Module._load (module.js:312:12)
>     at Module.require (module.js:362:17)
>     at require (module.js:378:17)
>     at repl:1:10
>     at REPLServer.self.eval (repl.js:111:21)
>     at Interface.<anonymous> (repl.js:250:12)
>     at Interface.EventEmitter.emit (events.js:88:17)
>     at Interface._onLine (readline.js:199:10)

**Comment by jussi-kalliokoski** [comment]
Yeah, you probably need to either configure `$LIBPATH` to include `/usr/local/lib` (or wherever cubeb installed its libraries), or if you don't mind being intrusive, just `# cp /usr/local/lib/libcubeb.so /usr/local/lib/libcubeb.so.0 /usr/lib/`. Haven't used Ubuntu for a while so I'm not quite sure if and how it differs from Arch when it comes to finding shared objects, so let me know if neither of those works.

**Comment by NHQ** [comment]
Ok. got it all hooked up. I tried to run the example in the readme (fixing a couple of variables refs but otherwise line for line), but the process just quit and that was it. 

However, test/sine-tone worked, so thats good!

**Comment by jussi-kalliokoski** [comment]
Yeah, in node the process dies if you don't have something to keep it alive, for example an HTTP connection or a timer, so you can probably just do `setInterval(function(){}, 10000)` to keep it from exiting.

I should fix the readme example. :D
